"""Renders the eight audit sections (spec section 11) into
docs/audits/YYYY-MM-DD-audit.md. Never edits project content -- read-only
analysis in, Markdown report out. The owner disposes."""


def _section(title, lines):
    body = "\n".join(lines) if lines else "None found."
    return "## {}\n\n{}\n".format(title, body)


def render_report(today_str, stale, broken_refs, orphans, growth, duplicates, contradictions, lint_drift, term_drift):
    parts = ["# Weekly audit -- {}\n".format(today_str),
             "Auto-generated by `tools/weekly_audit.py`. Proposes only; nothing here is auto-applied.\n"]

    parts.append(_section("1. Stale rows (past review_by, ACTIVE)", [
        "- `{}` in `{}` -- review_by was {} days ago".format(r["id"], r["file"], r["days_overdue"]) for r in stale
    ]))

    parts.append(_section("2. Broken references (spec section 8.8)", [
        "- `{}` {} -- {}".format(f.get("row_id", "?"), f["rule"], f["message"]) for f in broken_refs
    ]))

    parts.append(_section("3. Orphans (ACTIVE, unreferenced anywhere else)", [
        "- `{}` in `{}` -- {}".format(o["id"], o["file"], o["decision"]) for o in orphans
    ]))

    growth_lines = []
    for g in growth:
        delta = "n/a (no prior snapshot)" if g["delta_since_last_week"] is None else "{:+d}".format(g["delta_since_last_week"])
        line = "- `{}`: {} rows (change since last week: {})".format(g["file"], g["rows"], delta)
        if g.get("over_budget"):
            line += " -- **OVER BUDGET: {}**".format(g["over_budget"])
        growth_lines.append(line)
    parts.append(_section("4. Growth (row counts vs budget)", growth_lines))

    parts.append(_section("5. Near-duplicate statements (Jaccard > 0.6)", [
        "- {:.0%} similar: `{}` ({}) <-> `{}` ({})".format(p["similarity"], p["a"]["id"], p["a"]["file"], p["b"]["id"], p["b"]["file"])
        for p in duplicates
    ]))

    parts.append(_section("6. Contradiction candidates (advisory only)", [
        "- `{}` ({}) vs `{}` ({}) -- shared: {}".format(c["a"]["id"], c["a"]["file"], c["b"]["id"], c["b"]["file"], ", ".join(c["shared_words"]))
        for c in contradictions
    ]))

    drift, current_snapshot = lint_drift
    lint_lines = ["- Current: {} errors, {} warnings, {} review, smell_density={}".format(
        current_snapshot["summary"]["errors"], current_snapshot["summary"]["warnings"],
        current_snapshot["summary"]["review"], current_snapshot["summary"]["smell_density"])]
    if drift["delta"]:
        d = drift["delta"]
        lint_lines.append("- Since last week: errors {:+d}, warnings {:+d}, smell_density {:+.4f}".format(
            d["errors_change"], d["warnings_change"], d["smell_density_change"]))
    else:
        lint_lines.append("- No prior snapshot; this is the baseline.")
    parts.append(_section("7. Lint drift", lint_lines))

    parts.append(_section("8. Terminology drift (5+ uses, not in terminology.csv)", [
        "- `{}` -- {} uses".format(t["word"], t["count"]) for t in term_drift
    ]))

    return "\n".join(parts)
